### ISSUE TITLE
How to close steam correctly?

### ISSUE THREAD

**Issue by chihkang** [domschl/WinSteamOnMac#10]
with command Line Tools version 15.1 to build `game_porting_toolit` correctly.
I found even I close steam, it will appear again.
I need to kill all process start with wine in activity monitor, then the terminal process could stop with control + c
is it correctly ? or I need to follow some other steps I missing?

**Comment by domschl** [comment]
- Did that happen right after installation? If yes, reboot and retry again.

'Normal' behavior should be:

- In Steam GUI select 'Files / Exit' (Alternative: in menu bar, right-click steam icon, 'Exit Steam')
- The Steam GUI should display "Shutting down Steam", and after 1-2 seconds the processes (including the Icon in menu bar) should terminate.

At this point there should be no left-over processes from steam.

Additionally I had switched off the option "Steam / Settings / Interface": "Run Steam when my Computer starts", so I haven't tested, if that makes any difference.

**Comment by chihkang** [comment]
> * Did that happen right after installation? If yes, reboot and retry again.
> 
> 'Normal' behavior should be:
> 
> * In Steam GUI select 'Files / Exit' (Alternative: in menu bar, right-click steam icon, 'Exit Steam')
> * The Steam GUI should display "Shutting down Steam", and after 1-2 seconds the processes (including the Icon in menu bar) should terminate.
> 
> At this point there should be no left-over processes from steam.
> 
> Additionally I had switched off the option "Steam / Settings / Interface": "Run Steam when my Computer starts", so I haven't tested, if that makes any difference.

Thanks for your reply !
I have already reboot when installation . seems like I use wrong way to close steam.
It works ~ but if only click Steam's upper right corner `X` it will loop
close steam -> restart steam.
Maybe could add some hint at guide 👍

**Comment by domschl** [comment]
I've added a chapter 'Closing steam', thanks!
