### ISSUE TITLE
Do not use the placeholder "your-user-name"

### ISSUE THREAD

**Issue by AlexeyPechnikov** [domschl/WinSteamOnMac#4]
Replace it using $(whoami) to automatically detect username in terminal.

**Comment by cdtj** [comment]
created pull request upon the issue

https://github.com/domschl/WinSteamOnMac/pull/7

**Comment by domschl** [comment]
Sorry I had done conflicting edits, but I took both of your advices and eliminated the `your-user-name` simply using `~` instead of `/Users/<your-user-name`.

Thank you!

**Comment by cdtj** [comment]
haha, that's even better :)

**Comment by AlexeyPechnikov** [comment]
Please pay attention that “~” does not work always because it depends on shell substitution. It would be valuable to note that user might replace it to the hard-coded path in case of issues in Apple shortcuts, etc.

**Comment by domschl** [comment]
You are right in general, that was one of the reasons why I was lazy with `your-user-name` in the first place ;-)

I've tested the `~` in shortcuts and it seems to work fine!
