### ISSUE TITLE
"crash server failed to launch, self-terminating"?

### ISSUE THREAD

**Issue by isaacchan15947** [domschl/WinSteamOnMac#8]
I followed all steps and was patience in the last steps. After I waited for around 2 hours, I realized that I kept receiving the same error message "[0122/023753.742:ERROR:crashpad_client_win.cc(132)] crash server failed to launch, self-terminating" every 1 minutes.

Is it normal? How long should I wait for the first time? I tried rebooting the Mac and started Steam again after waiting for 2 hours, but it didn't help.

<img width="1512" alt="Screenshot 2024-01-22 at 02 39 39" src="https://github.com/domschl/WinSteamOnMac/assets/146573815/d43101bd-ca92-4ff4-8485-924dfbca8c7d">

**Comment by domschl** [comment]
Did you continue with:

   - Reboot(!) (There seem to be rogue processes that prevent successful
   retries without reboot)
   - And after reboot, open 'Terminal' and start Steam directly:



Am Mo., 22. Jan. 2024 um 08:44 Uhr schrieb isaacchan15947 <
***@***.***>:

**Comment by isaacchan15947** [comment]
Yes. I rebooted my Mac after 2 hours of waiting. After rebooting, I opened 'Terminal' and started Steam again, but it still ran the same "crash server failed to launch, self-terminating" sentence to me (The screenshot was taken after I rebooted and started Steam again).

Also, I tried to run the IE browser in the Program Files (x86) folder. The IE browser worked properly. So I don't know why Steam isn't running. 

By the way, I see the Steam icon on the Dock after I run it the second time. It has no available window for me though.

<img width="145" alt="Screenshot 2024-01-22 at 03 06 03" src="https://github.com/domschl/WinSteamOnMac/assets/146573815/ad9e67b2-aaa8-4814-a06e-570dcdab614c">

**Comment by domschl** [comment]
Did you install wine manually? If yes, please remove it completely and use only the version that is installed via Apple's game toolkit.

**Comment by isaacchan15947** [comment]
> Did you install wine manually? If yes, please remove it completely and use only the version that is installed via Apple's game toolkit.

I don't remember if I installed Wine manually since I followed the steps and never installed programs through Terminal. 

How can I check the version of Wine? And which version should it be?

**Comment by domschl** [comment]
I've re-checked that everything still works with latest steam and current Apple Game Porting Toolkit, and it's still ok.

If I enter in terminal:
```bash
/usr/local/bin/wine64 --version
```

I get:
```
wine-7.7
```

Anyway,

what I would recommend at this point is to follow the `Uninstallation notes` at the end and restart with a fresh installation from scratch.

**Comment by isaacchan15947** [comment]
> `wine-7.7`

I got wine-7.7 too.
After I uninstalled and reinstalled everything, it is working for me now :)
Maybe I used Xcode 15.2 previously, but the latest Command Line Tools was 15.1.
Right now, I am using Xcode 15.1 instead.

Thanks for answering my question and writing the steps here!
